debug: false
max-speed: 12
tool-item: 271
sign-radius: 3
sign-can-define-type: false
slow-when-empty: false
routingblocks:
- title: Booster
  block: 41
  acceleration:
  - ignoreredstone: false
  - redstone: true
  - speed: 250
  - relative: false
  acceleration:
  - ignoreredstone: false
  - redstone: false
  - speed: 10
  - relative: false
- title: Station
  block: 49
  launcher:
  - ignoreredstone: false
  - redstone: true
  - speed: 10
  - relative: false
  catcher:
  - ignoreredstone: false
  - redstone: false
- title: Switch
  block: 42
  switch:
  - ignoreredstone: true
  - redstone: true