name: MinecartRouting
main: MinecartRouting.MinecartRouting
version: 0.3.3
permissions:
    minecartrouting.create.*:
        description: Allows player to create/modify all kind of Routingblocks
        default: op
        children:
            minecartrouting.create.*.own: true
            minecartrouting.create.*.other: true
    minecartrouting.create.*.own:
        description: Allows player to create/modify own Routingblocks
        children:
            minecartrouting.create.acceleration.own: true
            minecartrouting.create.launcher.own: true
            minecartrouting.create.catcher.own: true
            minecartrouting.create.switch.own: true
    minecartrouting.create.*.other:
        description: Allows player to modify others Routingblocks
        children:
            minecartrouting.create.acceleration.other: true
            minecartrouting.create.launcher.other: true
            minecartrouting.create.catcher.other: true
            minecartrouting.create.switch.other: true
    
    minecartrouting.break.*:
        description: Allows player to break all kind of Routingblocks
        default: op
        children:
            minecartrouting.break.*.own: true
            minecartrouting.break.*.other: true
    minecartrouting.break.*.own:
        description: Allows player to break own Routingblocks
        children:
            minecartrouting.break.acceleration.own: true
            minecartrouting.break.launcher.own: true
            minecartrouting.break.catcher.own: true
            minecartrouting.break.switch.own: true
    minecartrouting.break.*.other:
        description: Allows player to break others Routingblocks
        children:
            minecartrouting.break.acceleration.other: true
            minecartrouting.break.launcher.other: true
            minecartrouting.break.catcher.other: true
            minecartrouting.break.switch.other: true
    
    minecartrouting.benefit.*:
        description: Allows player to benefit from all kind of Routingblocks
        default: true
        children:
            minecartrouting.benefit.*.own: true
            minecartrouting.benefit.*.other: true
    minecartrouting.benefit.*.own:
        description: Allows player to benefit from own Routingblocks
        children:
            minecartrouting.benefit.acceleration.own: true
            minecartrouting.benefit.launcher.own: true
            minecartrouting.benefit.catcher.own: true
            minecartrouting.benefit.switch.own: true
    minecartrouting.benefit.*.other:
        description: Allows player to benefit from others Routingblocks
        children:
            minecartrouting.benefit.acceleration.other: true
            minecartrouting.benefit.launcher.other: true
            minecartrouting.benefit.catcher.other: true
            minecartrouting.benefit.switch.other: true
    
    minecartrouting.create.acceleration.own:
        description: Allows player to create/modify own blocks with acceleration flag
    minecartrouting.create.launcher.own:
        description: Allows player to create/modify own blocks with launcher flag
    minecartrouting.create.catcher.own:
        description: Allows player to create/modify own blocks with catcher flag
    minecartrouting.create.switch.own:
        description: Allows player to create/modify own blocks with switch flag
        
    minecartrouting.create.acceleration.other:
        description: Allows player to modify others blocks with acceleration flag
    minecartrouting.create.launcher.other:
        description: Allows player to modify others blocks with launcher flag
    minecartrouting.create.catcher.other:
        description: Allows player to modify others blocks with catcher flag
    minecartrouting.create.switch.other:
        description: Allows player to modify others blocks with switch flag
    

    minecartrouting.break.acceleration.own:
        description: Allows player to break own blocks with acceleration flag
    minecartrouting.break.launcher.own:
        description: Allows player to break own blocks with launcher flag
    minecartrouting.break.catcher.own:
        description: Allows player to break own blocks with catcher flag
    minecartrouting.break.switch.own:
        description: Allows player to break own blocks with switch flag
        
    minecartrouting.break.acceleration.other:
        description: Allows player to break others blocks with acceleration flag
    minecartrouting.break.launcher.other:
        description: Allows player to break others blocks with launcher flag
    minecartrouting.break.catcher.other:
        description: Allows player to break others blocks with catcher flag
    minecartrouting.break.switch.other:
        description: Allows player to break others blocks with switch flag
        
    
    minecartrouting.benefit.acceleration.own:
        description: Allows player to use own blocks with acceleration flag
    minecartrouting.benefit.launcher.own:
        description: Allows player to use own blocks with launcher flag
    minecartrouting.benefit.catcher.own:
        description: Allows player to use own blocks with catcher flag
    minecartrouting.benefit.switch.own:
        description: Allows player to use own blocks with switch flag
        
    minecartrouting.benefit.acceleration.other:
        description: Allows player to use others blocks with acceleration flag
    minecartrouting.benefit.launcher.other:
        description: Allows player to use others blocks with launcher flag
    minecartrouting.benefit.catcher.other:
        description: Allows player to use others blocks with catcher flag
    minecartrouting.benefit.switch.other:
        description: Allows player to use others blocks with switch flag